server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /api/ntf-svc

spring:
  mail:
    host: smtp.gmail.com
    username: youremail@gmail.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

env:
  twilio:
    sms:
      authToken: ${AUTH_TOKEN:e9***********************}
      accountSid: ${ACCOUNT_SID:AC6*************************}
      fromNo: ${FROM_NUMBER:+120***********}

